name: Lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    name: Lint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: biomejs/setup-biome@v2
      - uses: actions/checkout@v4
      - run: biome ci .