name: Playwright Tests
on:
  push:
    branches: [master, playwright, visual-testing]
  pull_request:
    branches: [master]
jobs:
  test:
    name: "Test Chrome Extension"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.32.3-focal
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build extension
        run: npm run build
      - name: Install Playwright Chromium Browser
        run: npx playwright install chromium
      - name: Run Playwright tests
        run: xvfb-run --auto-servernum npx playwright test
